version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment

formatters:
  enable:
    - gofmt
    - goimports

run:
  tests: true
